### ISSUE TITLE
Look into smds for categorical variables 

### ISSUE THREAD

**Issue by LucyMcGowan** [malcolmbarrett/tidysmd#6]
We saw some unexpected (to me) behavior in the smd for ticket season when using the seven dwarfs data from the touringplans package in the most recent workshop (a single smd vs one for each category) — maybe this is standard from the smd package?

**Comment by malcolmbarrett** [comment]
Yeah, this appears to be an smd thing. factor is different than the numeric version, though, which implies something different is happening

``` r
mtcars2 <- mtcars
mtcars2$cyl <- factor(mtcars$cyl)
mtcars2$am <- factor(mtcars$am)
mtcars3 <- as.data.frame(model.matrix( ~ am + cyl, mtcars2))

# use numeric
smd::smd(mtcars$cyl, mtcars$am)
#>   term estimate
#> 1    1 1.249014

# use factors. 
smd::smd(mtcars2$cyl, mtcars2$am)
#>   term estimate
#> 1    1 1.250576

# use dummy variables
smd::smd(mtcars3$cyl6, mtcars3$am1)
#>   term    estimate
#> 1    1 -0.04882989
smd::smd(mtcars3$cyl8, mtcars3$am1)
#>   term estimate
#> 1    1 1.121574
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by malcolmbarrett** [comment]
I can't file an issue on their repo ⭕

**Comment by malcolmbarrett** [comment]
I found a GitHub repo but their DESCRIPTION file includes a link to an internal GitLab repo 🤔 

Anyway, this seems to be what it's doing with factors. Can you make heads or tails of this? https://github.com/novisci/smd/blob/a278e61dd59bed191f3f34bd3af204f62bb65acd/tests/testthat/test_smd.R#L51-L63

**Comment by malcolmbarrett** [comment]
ah, here's some more info from a [reference on their readme](https://www.lerner.ccf.org/qhs/software/lib/stddiff.pdf)

> For categorical baseline variables with *k* levels, Dalton (2008) proposed to use a multivariate
Mahalanobis distance method to generalize the standardized difference metric to handle a multinomial

**Comment by malcolmbarrett** [comment]
One option is to include an argument in `tidy_smd()` e.g. `dummy_variables = FALSE` which would, if `TRUE`, apply `model.matrix()` to dummify categorical variables. Thoughts, @LucyMcGowan?

**Comment by LucyMcGowan** [comment]
I think that sounds perfect! I can see utility in both measures, but I’m more used to the dummy version so it would be nice to have the option!
